services:
  api:
    build: ./backend-net
    ports:
      - "5000:8080"
    volumes:
      # Kita buat folder 'db-data' di VPS yang terhubung ke folder '/app/Database' di Docker
      - ./db-data:/app/Database
    restart: always